#
# Copyright (C) 2022 Vaticle
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

version: 2.1
orbs:
  win: circleci/windows@2.0.0
commands:

  install-bazel-linux-arm64:
    steps:
      - run: curl -OL https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-arm64
      - run: sudo mv bazelisk-linux-arm64 /usr/local/bin/bazel
      - run: chmod a+x /usr/local/bin/bazel

  install-bazel-linux-x86_64:
    steps:
      - run: curl -OL https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-amd64
      - run: sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
      - run: chmod a+x /usr/local/bin/bazel

  install-bazel-mac:
    steps:
      - run: brew install bazelisk

  install-requirements:
    steps:
      - run: |
          python3 -m pip install pip==23.2.1
          python3 -m pip install -r python/requirements_dev.txt

  deploy-pip-unix:
    steps:
      - run: |
          export DEPLOY_PIP_USERNAME=$REPO_VATICLE_USERNAME
          export DEPLOY_PIP_PASSWORD=$REPO_VATICLE_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //python:deploy-pip39 -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //python:deploy-pip310 -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //python:deploy-pip311 -- snapshot

  test-deployment-unix:
    steps:
      - run: |
          bazel run //tool/test:typedb-extractor -- typedb-all
          ./typedb-all/typedb server &
          python3 -m pip install wheel
          python3 -m pip install --extra-index-url https://repo.vaticle.com/repository/pypi-snapshot/simple typedb-client==0.0.0+$(git rev-parse HEAD)
          cd python/tests/deployment/ && python3 -m unittest test && export TEST_SUCCESS=0 || export TEST_SUCCESS=1
          kill $(jps | awk '/TypeDBServer/ {print $1}')
          exit $TEST_SUCCESS

jobs:
  deploy-mac-x86_64:
    macos:
      xcode: "14.2.0"
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - install-bazel-mac
      - install-requirements
      - deploy-pip-unix
      - test-deployment-unix

  deploy-mac-arm64:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.medium.gen1
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - install-bazel-mac
      - install-requirements
      - deploy-pip-unix
      - test-deployment-unix

  deploy-linux-arm64:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.medium
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - install-bazel-linux-arm64
      - install-requirements
      - deploy-pip-unix
      - test-deployment-unix

  deploy-linux-x86_64:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - install-bazel-linux-x86_64
      - install-requirements
      - deploy-pip-unix
      - test-deployment-unix

  deploy-windows-x86_64:
    executor:
      name: win/default
      shell: cmd.exe
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - run: .circleci\windows\prepare.bat
      - run: .circleci\windows\deploy.bat
      - run: .circleci\windows\test_deploy.bat

  test-deployment-mac-x86_64:
    macos:
      xcode: "14.2.0"
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - install-bazel-mac
      - install-requirements
      - test-deployment-unix

  test-deployment-mac-arm64:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.medium.gen1
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - install-bazel-mac
      - install-requirements
      - test-deployment-unix

  test-deployment-linux-arm64:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.medium
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - install-bazel-linux-arm64
      - install-requirements
      - test-deployment-unix

  test-deployment-linux-x86_64:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - install-bazel-linux-x86_64
      - install-requirements
      - test-deployment-unix

  test-deployment-windows-x86_64:
    executor:
      name: win/default
      shell: cmd.exe
    working_directory: ~/typedb-driver-java
    steps:
      - checkout
      - run: .circleci\windows\prepare.bat
      - run: .circleci\windows\test_deploy.bat


workflows:
  typedb-driver-python:
    jobs:
      - deploy-mac-x86_64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
      - deploy-mac-arm64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
      - deploy-linux-arm64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
      - deploy-linux-x86_64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
      - deploy-windows-x86_64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
      - test-deployment-mac-x86_64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
          requires:
            - deploy-mac-x86_64
      - test-deployment-mac-arm64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
          requires:
            - deploy-mac-arm64
      - test-deployment-linux-arm64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
          requires:
            - deploy-linux-arm64
      - test-deployment-linux-x86_64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
          requires:
            - deploy-linux-x86_64
      - test-deployment-windows-x86_64:
          filters:
            branches:
              only:
                - master
                - development
                - multiplatform-deploy-pip
          requires:
            - deploy-windows-x86_64
